<a href="https://colab.research.google.com/github/usmanbhatti1947/python-basics-assignment/blob/main/numpy_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
students = np.array(["Alice", "Bob", "Charlie", "David", "Emma"])

In [3]:
students.shape

(5,)

In [4]:
students.size

5

In [32]:
type(students)

numpy.ndarray

In [34]:
scores = np.array([
[85, 78, 92],
[88, np.nan, 80],
[75, 85, 79],
[np.nan, 90, 82],
[89, 76, 91]
])

In [7]:
type(scores)

numpy.ndarray

In [35]:
scores.shape

(5, 3)

In [36]:
scores.size

15

In [10]:
attendance = np.array([90, 85, 95, np.nan, 88])

In [11]:
attendance.shape

(5,)

In [12]:
attendance.size

5

In [13]:
type(attendance)

numpy.ndarray

##Data cleaning and handling missing values
###cahnging nan values in scores with mean value

In [37]:
# scores[np.isnan(scores)] #return an array of nan values
scores

array([[85., 78., 92.],
       [88., nan, 80.],
       [75., 85., 79.],
       [nan, 90., 82.],
       [89., 76., 91.]])

In [38]:
column_score_0 = scores[ : ,0] # ignoring nan value find mean value at 0 index of column
column_score_0


# scores[3,0] = mean_value
# scores

array([85., 88., 75., nan, 89.])

In [39]:
sum_value_0 = np.nansum(column_score_0)
sum_value_0

337.0

In [40]:
mean_value_0 = sum_value_0/5
scores[3,0] = mean_value_0
scores

array([[85. , 78. , 92. ],
       [88. ,  nan, 80. ],
       [75. , 85. , 79. ],
       [67.4, 90. , 82. ],
       [89. , 76. , 91. ]])

In [41]:
column_score_1 = scores[ : ,1] # ignoring nan value find mean value at 1 index of column
column_score_1

array([78., nan, 85., 90., 76.])

In [42]:
sum_value_1 = np.nansum(column_score_0)
sum_value_1

404.4

In [60]:
mean_value_1 = sum_value_1/5
scores[1,1] = mean_value_1
scores

array([[85.  , 78.  , 92.  ],
       [88.  , 80.88, 80.  ],
       [75.  , 85.  , 79.  ],
       [67.4 , 90.  , 82.  ],
       [89.  , 76.  , 91.  ]])

In [61]:
#Repalcing nan value with mean
# scores[np.isnan(scores)] = mean_value
# scores

###Changing nan values with mean in attendance

In [62]:
attendance_mean = np.nanmean(attendance)
attendance_mean

89.5

In [63]:
attendance[np.isnan(attendance)] = attendance_mean
attendance

array([90. , 85. , 95. , 89.5, 88. ])

##Calculate mean median std score of students

In [64]:
np.mean(scores)

82.55199999999999

In [65]:
np.median(scores)

82.0

In [66]:
np.std(scores)

6.692502471671812

In [67]:
np.max(scores)

92.0

In [68]:
average_score = np.mean(scores , axis=1) #average score for each student
average_score

array([85.        , 82.96      , 79.66666667, 79.8       , 85.33333333])

In [77]:
total_scores = np.sum(scores, axis=1)
performer_index = np.argmax(total_scores) #argmax method return first occurrences in case of multiple max values
top_performer = students[performer_index]
top_performer

'Emma'

In [76]:
# for i in range(len(students)):
#     print(f"{students[i]}: {average_score[i]}")

##Reshaping and broadcasting for data analysis

###Normalize student scores using min-max scaling:

In [80]:
min_score = np.nanmin(scores, axis=0)
# min_score
max_score = np.nanmax(scores, axis=0)


In [81]:
normalized_scores = (scores - min_score) / (max_score - min_score)
normalized_scores

array([[0.81481481, 0.14285714, 1.        ],
       [0.9537037 , 0.34857143, 0.07692308],
       [0.35185185, 0.64285714, 0.        ],
       [0.        , 1.        , 0.23076923],
       [1.        , 0.        , 0.92307692]])

In [82]:
np.shape(scores)

(5, 3)

In [85]:
# Reshape the scores array into 3D format to simulate multiple sections/classes.
scores_reshape = scores.reshape((1, 3, 5))
scores_reshape
# scores_reshape = np.reshape(scores, (1,3,5))
# scores_reshape

array([[[85.  , 78.  , 92.  , 88.  , 80.88],
        [80.  , 75.  , 85.  , 79.  , 67.4 ],
        [90.  , 82.  , 89.  , 76.  , 91.  ]]])

###Bonus 5 score for students less than 80 in any subject

In [86]:
bonus_scores = np.where(scores < 80, scores + 5, scores)
bonus_scores

array([[85.  , 83.  , 92.  ],
       [88.  , 80.88, 80.  ],
       [80.  , 85.  , 84.  ],
       [72.4 , 90.  , 82.  ],
       [89.  , 81.  , 91.  ]])

In [92]:
score_attendance_stack = np.hstack([scores, attendance])
score_attendance_stack

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [96]:
reshaped_attendance = attendance.reshape(-1,1)
reshaped_attendance

array([[90. ],
       [85. ],
       [95. ],
       [89.5],
       [88. ]])

In [97]:
score_attendance_stack = np.hstack([scores, reshaped_attendance])
score_attendance_stack

array([[85.  , 78.  , 92.  , 90.  ],
       [88.  , 80.88, 80.  , 85.  ],
       [75.  , 85.  , 79.  , 95.  ],
       [67.4 , 90.  , 82.  , 89.5 ],
       [89.  , 76.  , 91.  , 88.  ]])

In [99]:
split_data = np.split(score_attendance_stack,2, axis=1)
split_data

[array([[85.  , 78.  ],
        [88.  , 80.88],
        [75.  , 85.  ],
        [67.4 , 90.  ],
        [89.  , 76.  ]]),
 array([[92. , 90. ],
        [80. , 85. ],
        [79. , 95. ],
        [82. , 89.5],
        [91. , 88. ]])]